# Learning NumPy from Basic

- It is Linear Algebra Library (also called as Numerical Python) <br>

# -----------Arrays-----------

### Creating a numpy array <br>
array() method is used to create an array in numpy

In [22]:
# importing numpy library
import numpy as np

print(np.array([10,12,13,14,15]))

[10 12 13 14 15]


- arange(start,end,step) can be used to create a array of given range

In [25]:
#creating array from 0 to 9
arr1 = np.arange(0,10)

#creating array from 10 to 19
arr2 = np.arange(10,20)

#creating a list to create a list of list in order to create 2d numpy array
list = [arr1,arr2]

#passing the list to array() method to create a numpy array
np.array(list)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

- **zeros((rows,columns))**
- **ones((rows,columns))** <br>
the above two methods are used to create a numpy array of zeros and ones respectively

In [30]:
# 4 rows of zeros will be created

np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
# pass a tuple to create 2d array of zeros

np.zeros((4,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [33]:
# 3 rows of ones will be created

np.ones(3)

array([1., 1., 1.])

In [34]:
# pass a tuple to create 2d array of ones

np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### **linspace(start,end,even_space_required)**


**linspace is used to create an array from start to end with the number provided as evenly spaced between them**

In [38]:
# all the 10 numbers are evenly spaced float numbers between them

np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

## Creating Identity Matrix
- eye(n) will create an identity matrix of dimesions 'n**x**n' 

In [39]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Creating Array of Random numbers

- by **random.rand()** method <br>
it will populate the array with the numbers in uniform distribution

2d array of random numbers

In [46]:
np.random.rand(5)

array([0.76316953, 0.08347739, 0.45517834, 0.87214646, 0.42334385])

3d array of random numbers <br>
note: instead of tuples directly pass dimensions

In [44]:
np.random.rand(4,2)

array([[0.75042299, 0.86272329],
       [0.52160915, 0.14015062],
       [0.05600334, 0.726741  ],
       [0.60277593, 0.4958444 ]])

- by **random.randn()** method <br>
it will populate the array with the numbers in normal or guassian  distribution

In [47]:
np.random.randn(3)

array([-0.81483643, -1.51369483, -0.79426333])

In [48]:
np.random.randn(3,2)

array([[ 0.33023524, -1.30769305],
       [-1.01595651, -0.61574764],
       [ 0.40959567, -0.42574715]])

- by **random.randint()** method <br>
it will populate the array with the integer types of number from low to high numbers <br>
randint(low,high,n) where, <br>
low is inclusive and high is exclusive <br>
n is the number of random numbers you want to generate

In [52]:
 np.random.randint(1,100,5)

array([13, 53, 25, 71, 10])

## - Attributes and Methods of Array

Lets first create an array to operate on it

In [62]:
my_array = np.arange(20)   # array of 0 to 19 is integers is created
my_rand_array = np.random.randint(0,100,20) # random integer array is created of 20 numbers ranging from 0 to 100

In [58]:
my_array.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [65]:
print(my_rand_array)        # printing the random array

[26  4 22 21  9 28 94 48 41 25 76 52 45 85 58 14 60 54 62 78]


- **Finding minimum and maximum element from array**

In [66]:
print(my_rand_array.max())  # printing the max element of array
print(my_rand_array.min())  # printing the min element of array

94
4


- **Finding the index of minimum and maximum element from array**

In [68]:
print(my_rand_array.argmax())
print(my_rand_array.argmin())

6
1


Knowing the shape/dimensions of the array/vector

In [71]:
my_array.shape

(20,)

Knowing the datatype of the array

In [74]:
my_array.dtype

dtype('int32')

# -----------Indexing and Selection-----------

In [79]:
arr = np.arange(0,11)

**Accessing specific element**

In [77]:
arr[1] 

1

**Particular range**

In [80]:
arr[1:5]

array([1, 2, 3, 4])

In [81]:
arr[:5]

array([0, 1, 2, 3, 4])

In [82]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

**Creating a slice of original array**

In [83]:
slice = arr[:5]

In [84]:
slice

array([0, 1, 2, 3, 4])

**Brodcating the value -1 to the given particular range slice**

In [85]:
slice [0:2] = -1

In [86]:
slice

array([-1, -1,  2,  3,  4])

In [87]:
arr

array([-1, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**As observed the change in the slice of array is reflected in original array** <br>
**Hence the slice is just a view of original array i.e reference, and not a copy** <br><br>
#### To create a copy we can do the following

In [88]:
copy = arr.copy()

In [89]:
copy

array([-1, -1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
arr = np.arange(0,11)

In [92]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

Copy of array if changed, i.e broadcasted like the way I did to the Slice of the array, the changes in this case won't be reflected to the original array

## Operations over 2D array

In [94]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Accessing 2d Array/ Matrix using: <br>
- Double bracket method 


In [96]:
arr_2d[1][0] # bracket 1 is row bracket 2 is column

4

- Single bracket with comma <br>
recommended to use by bootcamp instructor

In [99]:
arr_2d[1,0] #param 1 is row and param 2 is column

4

In [100]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [101]:
arr = np.arange(0,11)

In [102]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

**Displaying boolean type of array for given condition**

In [104]:
bool_arr = arr > 5

In [105]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

#### displaying the array as per satisfied condition

In [106]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

#### All the above operations performed in short hand way..... which is called as conditional selection

In [108]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [112]:
arr[arr<3]

array([0, 1, 2])

# -----------Basic Operations on NumPy Arrays-----------

#### Three Basic operations on NumPy arrays are:
- Array with Array
- Array with Scalars
- Universal Array Functions

In [113]:
ar1 = np.arange(0,11)

In [114]:
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Array with array
- Simply '+' operator can be used to add two arrays<br>
- All arithmetic operations can be done in same manner

In [126]:
ar1 + ar1

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [127]:
ar1 ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

#### Array with scalars
- Adding a scalar, i.e a number to an array is done as array + number, which will add the scalar to every element.<br>
- All arithmetic operations can be done in same manner

### Note: NumPy doesn't gives error on divide by 0 operation, instead it gives a warning and return "nan" or "inf" value for such operations

In [125]:
ar1 / ar1

C:\Users\ImSahil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

#### Universal Array Function
- These are basically mathematical broadcast Functions

In [128]:
np.sqrt(ar1)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [129]:
np.max(ar1)

10

In [130]:
np.min(ar1)

0

In [131]:
np.sin(ar1)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [134]:
np.cos(ar1)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

In [135]:
np.log(ar1)

C:\Users\ImSahil\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])